### ISSUE TITLE
Fails to shutdown when connection to DB is lost, then gets "stuck"

### ISSUE THREAD

**Issue by MV-GH** [noctarius/timescaledb-event-streamer#315]
I was testing the behaviour of what would happen if connection to the DB was lost. It seems to fail to shutdown and then gets in a stuck state. Where it doesn't do anything. Event when connection is restored.

![Image](https://github.com/user-attachments/assets/3d7ca57a-c262-4ded-942b-53a375f79326)

Reproduce steps:
- run streamer
- shutdown DB

**Comment by noctarius** [comment]
Let me see if I can get to this over the weekend and also get the new version out.

**Comment by MV-GH** [comment]
Hey, with the new version it isn't fixed. It gets stuck in "shutdown" phase and doesn't do anything, even when DB is restored.

Could you reopen this issue?

![Image](https://github.com/user-attachments/assets/f830caf6-26be-49d4-9534-daf3abc67e28)

**Comment by noctarius** [comment]
Sure thing but I'm really not sure where it would hang. Seems like I have to test it against a real database and hope I can find it.

**Comment by MV-GH** [comment]
If this is any help, This is the log with debug.

```
[2025/05/16T11:55:46.375] [DEBUG] [ReplicationHandler] EVENT: {messageType:Begin finalLSN:32F5/614000D8 commitTime:2025-05-16 11:55:46.380026 +0200 CEST xid:1544917915}  
[2025/05/16T11:55:46.375] [DEBUG] [ReplicationHandler] EVENT: {messageType:Commit flags:0 commitLSN:32F5/614000D8 transactionEndLSN:32F5/61400108 commitTime:2025-05-16 11:55:46.380026 +0200 CEST}  
[2025/05/16T11:55:46.375] [DEBUG] [EventEmitter] Transaction xid=1544917915 (LSN: 32F5/61400108) marked as processed  
[2025/05/16T11:55:46.375] [DEBUG] [ReplicationContext] Acknowledge transaction end: 32F5/61400108  
[2025/05/16T11:55:46.384] [FATAL] [ReplicationChannel] Issue handling WAL stream: ReceiveMessage failed: receive message failed: unexpected EOF  
[2025/05/16T11:55:46.384] [INFO] [ReplicationHandler] Starting to shutdown  
[2025/05/16T11:55:46.384] [ERROR] [ReplicationChannel] shutdown failed (drop replication slot): conn closed  
[2025/05/16T11:55:46.409] [ERROR] [ReplicationChannel] shutdown failed (drop publication): unable to connect to database: failed to connect to `user=postgres database=postgres`:
	[::1]:5532 (localhost): dial error: dial tcp [::1]:5532: connectex: No connection could be made because the target machine actively refused it.
	127.0.0.1:5532 (localhost): dial error: dial tcp 127.0.0.1:5532: connectex: No connection could be made because the target machine actively refused it.
	[::1]:5532 (localhost): dial error: dial tcp [::1]:5532: connectex: No connection could be made because the target machine actively refused it.
	127.0.0.1:5532 (localhost): dial error: dial tcp 127.0.0.1:5532: connectex: No connection could be made because the target machine actively refused it.  
```

**Comment by MV-GH** [comment]
Found the cause but don't know yet how to fix so that it follows the proper shutdown process.

The shutdown chain that get stuck:
- DB connection lost during a ReceiveMessage
- this code gets error `ReceiveMessage failed: receive message failed: read tcp [::1]:64522->`
```go
		go func() {
			err := handler.startReplicationHandler(replicationConnection, restartLSN)
			if err != nil {
				rc.logger.Fatalf("Issue handling WAL stream: %s", err)
			}
			rc.shutdownAwaiter.SignalShutdown()
		}()
```
- This signals the shutdown of ReplicationChannel
- Where it jumps to here
```go
	go func() {
		// Mark the current replication channel as shutting down
		rc.shutdownRequested.Store(true)

		if err := rc.shutdownAwaiter.AwaitShutdown(); err != nil { // Here to be precise
			rc.logger.Errorf("shutdown failed: %+v", err)
		}

		// Stop potentially started replication before going on
		stopReplication()

		if err := replicationConnection.DropReplicationSlot(); err != nil {
			rc.logger.Errorf("shutdown failed (drop replication slot): %+v", err)
		}
		if rc.createdPublication && rc.publicationManager.PublicationAutoDrop() {
			if err := rc.publicationManager.DropPublication(); err != nil {
				rc.logger.Errorf("shutdown failed (drop publication): %+v", err)
			}
		}
		if err := replicationConnection.Close(); err != nil {
			rc.logger.Warnf("failed to close replication connection: %+v", err)
		}
		rc.shutdownAwaiter.SignalDone()
	}()
```
- This signals then done
- It ends here as `StopReplicationChannel()` hasn't been called yet that awaits the previous Done

Normal shutdownProcedure

- streamer.Stop()
- s.replicator.StopReplication()
- Loops over shutdown tasks
- One of these is `replicationChannel.StopReplicationChannel()`
- This signals 	rc.shutdownAwaiter.SignalShutdown()
- Where it then jumps to this code
- Where it jumps to here
```go
	go func() {
		// Mark the current replication channel as shutting down
		rc.shutdownRequested.Store(true)

		if err := rc.shutdownAwaiter.AwaitShutdown(); err != nil { // Here to be precise
			rc.logger.Errorf("shutdown failed: %+v", err)
		}

		// Stop potentially started replication before going on
		stopReplication()

		if err := replicationConnection.DropReplicationSlot(); err != nil {
			rc.logger.Errorf("shutdown failed (drop replication slot): %+v", err)
		}
		if rc.createdPublication && rc.publicationManager.PublicationAutoDrop() {
			if err := rc.publicationManager.DropPublication(); err != nil {
				rc.logger.Errorf("shutdown failed (drop publication): %+v", err)
			}
		}
		if err := replicationConnection.Close(); err != nil {
			rc.logger.Warnf("failed to close replication connection: %+v", err)
		}
		rc.shutdownAwaiter.SignalDone()
	}()
```
- Jumps back to StopReplicationChannel task
- where it then completes other shutdownTasks
- ...

**Comment by noctarius** [comment]
Yeah, I'm also looking into it. The issue should be the side channel connection which is created to drop the publication. I'm thinking about a solution, but I might have to store the information that we were disconnected with "database shutdown" info to skip those. An alternative idea is to enable an option to say that for a shutdown, I only try to connect once for a side channel connection, if it fails, so what.

**Comment by noctarius** [comment]
Oh, but I just realized why my test didn't work. It fails on the droppublication, but my test had the autodrop disabled 🫣

**Comment by noctarius** [comment]
Still not hanging. Can you share your configuration? Not sure you've shared it before.

**Comment by MV-GH** [comment]
Sure, I'll share it. I think the drop publication is irrelevant. There must be load that is being streamed, and should fail on that. When the connection falls away

**Comment by MV-GH** [comment]
Full steps to reproduce it. (Works consistently for me)

docker-compose
```yaml
services:
  db:
    image: timescale/timescaledb-ha:pg14-ts2.13
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5888:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
```

the config
```toml
postgresql.connection = 'postgres://postgres@localhost:5888/postgres'
postgresql.password = 'postgres'
postgresql.publication.name = 'publication_event_streamer_local'
postgresql.publication.create = true
postgresql.replicationslot.name = 'replication_event_streamer_local'
postgresql.replicationslot.create = true
timescaledb.hypertables.includes = ['public.datapoints_15_min_buckets_local']
postgresql.events.message = false
timescaledb.events.read = false
sink.type = 'stdout'


logging.level = 'debug'
logging.outputs.console.enabled = true
logging.loggers.LogicalReplicationResolver.level = 'debug'
logging.loggers.LogicalReplicationResolver.outputs.console.enabled = true


stats.port = 8082

postgresql.transaction.window.maxsize = 100000
```

init.sql
```sql
CREATE TABLE datapoints_15_min_buckets_local
(
    asset_id          UUID        NOT NULL,
    timestamp         TIMESTAMPTZ NOT NULL,
    datapoint_type_id INT         NOT NULL,
    value             INTERVAL    NOT NULL
);

ALTER table datapoints_15_min_buckets_local REPLICA IDENTITY FULL;

SELECT create_hypertable('datapoints_15_min_buckets_local', by_range('timestamp'));

CREATE OR REPLACE PROCEDURE insert_random_datapoints()
    LANGUAGE plpgsql
AS
$$
DECLARE
    fixed_timestamp TIMESTAMPTZ := CURRENT_TIMESTAMP;
BEGIN
    LOOP
        CALL insert_one_datapoint(fixed_timestamp);
        PERFORM PG_SLEEP(1); -- Wait for 1 second
    END LOOP;
END;
$$;

CREATE OR REPLACE PROCEDURE insert_one_datapoint(_timestamp TIMESTAMPTZ)
    LANGUAGE plpgsql
AS
$$
DECLARE
BEGIN
    INSERT INTO datapoints_15_min_buckets_local (asset_id, timestamp, datapoint_type_id, value)
    VALUES (gen_random_uuid(), _timestamp, 3, INTERVAL '15 minutes');
    COMMIT;
END;
$$;
```

- Start db
- execute init script
- run that catalog script
- keep running`call insert_random_datapoints()` to generate load
- start streamer with above config
- kill DB

Then you should see the above error message and it being stuck
