### ISSUE TITLE
[Bug] properties for events to be generated do not seem to have an impact anymore

### ISSUE THREAD

**Issue by flexwende** [noctarius/timescaledb-event-streamer#63]
The properties that define which event get generated do not seem to have an impact anymore. All events seem to be captured regardless of the property. E.g. even though my config looks like below all events get captured (tested: insert, update, delete, truncate).

```toml
timescaledb.hypertables.excludes = []
timescaledb.hypertables.includes = ['public.event_table']
timescaledb.events.read = false
timescaledb.events.insert = false
timescaledb.events.update = false
timescaledb.events.delete = false
timescaledb.events.truncate = false
timescaledb.events.message = false
timescaledb.events.compression = false
timescaledb.events.decompression = false

postgresql.tables.excludes = []
postgresql.tables.includes = []
postgresql.events.read = false
postgresql.events.insert = false
postgresql.events.update = false
postgresql.events.delete = false
postgresql.events.truncate = false
postgresql.events.message = false
```

Versions:
- postgresql: 14
- timescaledb: 2.11.2
- timescaledb-event-streamer: 0.10.0
